export const JOB_ROLES = [
    "Software Engineer Intern",
    "Software Engineer (Entry Level)",
    "Senior Software Engineer",
    "Frontend Developer Intern",
    "Frontend Developer",
    "Senior Frontend Developer",
    "Backend Developer Intern",
    "Backend Developer",
    "Senior Backend Developer",
    "Full Stack Developer Intern",
    "Full Stack Developer",
    "Senior Full Stack Developer",
    "DevOps Engineer Intern",
    "DevOps Engineer",
    "Senior DevOps Engineer",
    "Data Scientist Intern",
    "Data Scientist",
    "Senior Data Scientist",
    "Data Analyst Intern",
    "Data Analyst",
    "Senior Data Analyst",
    "Machine Learning Engineer Intern",
    "Machine Learning Engineer",
    "Senior Machine Learning Engineer",
    "Product Manager Intern",
    "Associate Product Manager",
    "Product Manager",
    "Senior Product Manager",
    "UI/UX Designer Intern",
    "UI/UX Designer",
    "Senior UI/UX Designer",
    "QA Engineer Intern",
    "QA Engineer",
    "Senior QA Engineer",
    "Mobile App Developer (iOS) Intern",
    "Mobile App Developer (iOS)",
    "Mobile App Developer (Android) Intern",
    "Mobile App Developer (Android)",
    "Cloud Engineer Intern",
    "Cloud Engineer",
    "Cybersecurity Analyst Intern",
    "Cybersecurity Analyst",
    "Network Engineer",
    "System Administrator",
    "Database Administrator",
    "Business Analyst Intern",
    "Business Analyst",
    "Marketing Specialist",
    "Sales Representative",
    "HR Specialist",
];
